"""Add idempotency_key to transactions

Revision ID: 499ff1d4f265
Revises: ec49b8fb6c74
Create Date: 2026-08-30 02:53:08.904262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499ff1d4f265'
down_revision: Union[str, Sequence[str], None] = 'ec49b8fb6c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
